import type { Metadata } from "next";
import Navbar from "@/components/navbar/Navbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
        <main className="mb-5">
          {children}
        </main>
      </body>
    </html>
  );
}
